### PR TITLE
Use gcla/tail on Windows and tail command on unix

### LINKED ISSUE #76: Build code from gcla/tail only on Windows to allow Debian packaging
This is related to #74.

If we can ensure code from gcla/tail is only compiled on Windows (the only target for which it's needed), then gcla/tail won't need to be packaged for Debian, meaning termshark's Debian package can be updated.

CCing @dawidd6

### PR DESCRIPTION
**Pull request by dawidd6**
Closes: #76 

Tried my best, dunno if it's properly implemented, but tested it with `termshark --tail` and it worked.

### CODE REVIEW

**Comment by gcla** [comment]
Thank you! :-) I'll merge this. If you don't mind I might add a little extra to it - I was thinking of maybe going even further and removing the `--tail` switch from Unix builds altogether

**Comment by dawidd6** [comment]
Sure thing, I would only like to request a new patch release once it's done, so I can update the package and hopefully upload it :).

**Comment by gcla** [comment]
Will do!

**Comment by gcla** [comment]
Hi @dawidd6 - just pushed tag v2.0.3 - thanks!

**Pull request merged**
